"""initial schema

Revision ID: f4d976a14207
Revises: 
Create Date: 2026-06-22 16:35:11.898097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d976a14207'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('album_art_url', sa.String(length=1000), nullable=True),
    sa.Column('spotify_popularity', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('correct', 'wrong', 'gave_up', 'abandoned', name='sessionresult'), nullable=True),
    sa.Column('guessed_track_id', sa.String(), nullable=True),
    sa.Column('actual_track_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actual_track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guessed_track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attribute_key', sa.String(length=100), nullable=False),
    sa.Column('text_es', sa.String(length=500), nullable=False),
    sa.Column('text_en', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ask_count', sa.Integer(), nullable=False),
    sa.Column('yes_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_key'], ['attributes.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_key', 'text_es', name='uq_question_attr_text')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_attribute_key'), ['attribute_key'], unique=False)

    op.create_table('track_attributes',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('attribute_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('spotify', 'lastfm', 'claude', 'crowd', 'manual', name='attributesource'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_key'], ['attributes.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'attribute_key')
    )
    op.create_table('attribute_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('attribute_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_key'], ['attributes.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attribute_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attribute_votes_attribute_key'), ['attribute_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_votes_track_id'), ['track_id'], unique=False)

    op.create_table('suggested_tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('title_raw', sa.String(length=500), nullable=False),
    sa.Column('artist_raw', sa.String(length=500), nullable=False),
    sa.Column('spotify_track_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_tracks')
    with op.batch_alter_table('attribute_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attribute_votes_track_id'))
        batch_op.drop_index(batch_op.f('ix_attribute_votes_attribute_key'))

    op.drop_table('attribute_votes')
    op.drop_table('track_attributes')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_attribute_key'))

    op.drop_table('questions')
    op.drop_table('game_sessions')
    op.drop_table('tracks')
    op.drop_table('attributes')
    # ### end Alembic commands ###
